# Generated by Django 4.2.6 on 2023-11-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicinename', models.CharField(max_length=50)),
                ('medicinetype', models.CharField(max_length=50)),
                ('medicinestock', models.CharField(max_length=50)),
                ('medicineprice', models.CharField(max_length=50)),
            ],
        ),
    ]
