# Generated by Django 4.2.6 on 2023-11-22 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_sales'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='medicinename',
            new_name='customercontact',
        ),
        migrations.RenameField(
            model_name='sales',
            old_name='medicineqty',
            new_name='medicine',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='number',
        ),
    ]
